apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # Point at this cluster's case-file namespace.
  - target: {kind: Deployment, name: informant}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        value: http://frontdesk.case-file-staging.svc.cluster.local:8080
