apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - node-tuner-green.yaml
  - node-tuner-blue.yaml
images:
  - name: ghcr.io/dhpup/case-file
    digest: sha256:814ead981b03a2b30f188b6799d18fe6f360672c9777d0080e916235498aa1e2  # v1.2.0 (tuner mode)
