apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontdesk
  name: frontdesk
  namespace: case-file-staging
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 8080
  selector:
    app: frontdesk
  type: NodePort
