apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: evidence-locker
  namespace: case-file-prod
spec:
  endpoints:
  - interval: 10s
    port: http
  selector:
    matchLabels:
      app: evidence-locker
