apiVersion: v1
kind: Service
metadata:
  name: informant
  namespace: informant
  labels: {app: informant}
spec:
  selector: {app: informant}
  ports:
    - {name: metrics, port: 9090}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: informant
  namespace: informant
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels: {app: informant}
  endpoints:
    - {port: metrics, interval: 10s}
